  //1
  SELECT EMP_NAME, EMP_NO,DEPT_TITLE,JOB_NAME
  FROM EMPLOYEE E, DEPARTMENT D , JOB J
  WHERE E.JOB_CODE = J.JOB_CODE AND DEPT_ID = DEPT_CODE
  AND SUBSTR(EMP_NO,8,1) = 2
  AND SUBSTR(EMP_NO,0,1) = 7
  AND SUBSTR(EMP_NAME,0,1) = '전';  
  
  //2
  SELECT EMP_ID,EMP_NAME,EXTRACT(YEAR FROM SYSDATE)  - ('19'||SUBSTR(EMP_NO,1,2))  나이,DEPT_TITLE,JOB_NAME 
  FROM EMPLOYEE E, DEPARTMENT , JOB J
  WHERE E.JOB_CODE = J.JOB_CODE AND DEPT_ID = DEPT_CODE
  AND EMP_NO = (SELECT MAX(EMP_NO) FROM EMPLOYEE);
  
  //3
  SELECT EMP_ID,EMP_NAME,JOB_NAME
  FROM  EMPLOYEE E , JOB J
  WHERE E.JOB_CODE = J.JOB_CODE
  AND EMP_NAME LIKE '%하%';
  
  //4
  SELECT EMP_NAME,JOB_NAME,DEPT_CODE,DEPT_TITLE
  FROM EMPLOYEE E, DEPARTMENT , JOB J
  WHERE E.JOB_CODE = J.JOB_CODE AND DEPT_ID = DEPT_CODE
  AND DEPT_CODE IN('D5','D6');
  
  //5
  SELECT EMP_NAME,BONUS,DEPT_TITLE,LOCAL_NAME
  FROM EMPLOYEE,DEPARTMENT,LOCATION
  WHERE  DEPT_ID = DEPT_CODE AND LOCAL_CODE = LOCATION_ID
  AND BONUS IS NOT NULL;
  
  //6
  SELECT EMP_NAME,JOB_NAME,DEPT_TITLE,LOCAL_NAME
    FROM EMPLOYEE E, DEPARTMENT , JOB J,LOCATION
    WHERE  E.JOB_CODE = J.JOB_CODE AND DEPT_ID = DEPT_CODE AND LOCAL_CODE = LOCATION_ID;
    
//7
SELECT EMP_NAME,DEPT_TITLE,LOCAL_NAME,NATIONAL_NAME
FROM EMPLOYEE E, DEPARTMENT , JOB J,LOCATION L,NATIONAL N
WHERE  E.JOB_CODE = J.JOB_CODE AND DEPT_ID = DEPT_CODE AND LOCAL_CODE = LOCATION_ID AND L.NATIONAL_CODE = N.NATIONAL_CODE
AND NATIONAL_NAME IN('한국','일본');

//8
SELECT EMP_NAME, DEPT_CODE
FROM EMPLOYEE 
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME='하정연');

//9
SELECT EMP_NAME,JOB_NAME,SALARY,NVL(BONUS, 0) 보너스없음
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE JOB_CODE IN('J4','J7');

//10
SELECT COUNT(Y),COUNT(N) FROM EMPLOYEE
GROUP BY ENT_YN;